# Generated by Django 5.2.6 on 2025-10-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('gestor', 'Gestor'), ('profissional_saude', 'Profissional de Saúde'), ('pais', 'Pais/Responsáveis')], max_length=32),
        ),
    ]
