# Generated by Django 5.2.6 on 2025-11-05 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_user_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Filho",
        ),
    ]
