[project]
name = "karu"
version = "0.1.0"
description = ""
authors = [
    {name = "edeilsonazevedo",email = "edeilsonazavedo22@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django (>=5.2.6,<6.0.0)",
    "pytest (>=8.4.2,<9.0.0)",
    "pytest-django (>=4.11.1,<5.0.0)",
    "ruff (>=0.13.0,<0.14.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
line-length = 100
target-version = "py312"
extend-select = ["I"]       # abilita isort 
fix = true                  # corrigi de forma automática

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true    # não reclama de libs não tipadas
strict_optional = true           # força checagem de None
warn_unused_ignores = true    # avisa "ignore" inútil
warn_return_any = true           # alerta quando funções retornarem qualquer coisa
disallow_untyped_defs = true     # funções novas tipadas
files = ["."]
[tool.poetry.group.dev.dependencies]
pre-commit = "^4.3.0"


