# Generated by Django 5.2.6 on 2025-10-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailalert",
            name="status",
            field=models.CharField(
                choices=[
                    ("aguardando_envio", "Aguardando Envio"),
                    ("enviado", "Enviado"),
                    ("falha_envio", "Falha no Envio"),
                    ("cancelado", "Cancelado"),
                ],
                default="aguardando_envio",
                max_length=20,
            ),
        ),
    ]
