# Generated by Django 5.2.6 on 2025-09-29 12:44

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data/hora em que o registro foi criado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data/hora da ultima atualização"
                    ),
                ),
                (
                    "is_activate",
                    models.BooleanField(default=True, help_text="Indica se o registro está ativo"),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "sex",
                    models.CharField(choices=[("M", "Masculino"), ("F", "Feminino")], max_length=1),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        help_text="Somente números, sem pontos ou traços.",
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CPF deve ter 11 dígitos numéricos.", regex="^\\d{11}$"
                            )
                        ],
                    ),
                ),
                (
                    "birth_certificate_number",
                    models.CharField(
                        blank=True,
                        help_text="Número da certidão de nascimento (se disponível).",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("gestational_age_weeks", models.PositiveSmallIntegerField()),
                ("gestational_age_days", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("birth_weight", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "birth_length",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "head_circumference",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data/hora em que o registro foi criado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data/hora da ultima atualização"
                    ),
                ),
                (
                    "is_activate",
                    models.BooleanField(default=True, help_text="Indica se o registro está ativo"),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("discharge", "Alta"),
                            ("consultation", "Consulta"),
                            ("followup", "Seguimento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InterdisciplinaryEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data/hora em que o registro foi criado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data/hora da ultima atualização"
                    ),
                ),
                (
                    "is_activate",
                    models.BooleanField(default=True, help_text="Indica se o registro está ativo"),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("nursing", "Enfermagem"),
                            ("physiotherapy", "Fisioterapia"),
                            ("speech", "Fonoaudiologia"),
                            ("psychology", "Psicologia"),
                            ("social_work", "Serviço Social"),
                            ("occupational_therapy", "Terapia Ocupacional"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_evaluations",
                        to="patients.record",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data/hora em que o registro foi criado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data/hora da ultima atualização"
                    ),
                ),
                (
                    "is_activate",
                    models.BooleanField(default=True, help_text="Indica se o registro está ativo"),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                ("specialty", models.CharField(blank=True, max_length=50, null=True)),
                ("professional", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="patients.record",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data/hora em que o registro foi criado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data/hora da ultima atualização"
                    ),
                ),
                (
                    "is_activate",
                    models.BooleanField(default=True, help_text="Indica se o registro está ativo"),
                ),
                ("type", models.CharField(max_length=50)),
                ("result", models.TextField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("observations", models.TextField(blank=True, null=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="patients.record",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DischargeRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data/hora em que o registro foi criado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data/hora da ultima atualização"
                    ),
                ),
                (
                    "is_activate",
                    models.BooleanField(default=True, help_text="Indica se o registro está ativo"),
                ),
                ("chronological_age_days", models.PositiveIntegerField(blank=True, null=True)),
                ("corrected_age_weeks", models.PositiveIntegerField(blank=True, null=True)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "length",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "head_circumference",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "feeding_type",
                    models.CharField(
                        choices=[
                            ("breastfeeding", "SME"),
                            ("mixed", "SM+Fórmula"),
                            ("formula", "Fórmula"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discharge",
                        to="patients.record",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClinicalEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data/hora em que o registro foi criado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data/hora da ultima atualização"
                    ),
                ),
                (
                    "is_activate",
                    models.BooleanField(default=True, help_text="Indica se o registro está ativo"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("pediatric", "Pediátrica"),
                            ("neurologic", "Neurológica"),
                            ("cardiac", "Cardiológica"),
                            ("visual", "Visual"),
                            ("auditory", "Auditiva"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("normal", "Normal"), ("altered", "Alterada")], max_length=10
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_evaluations",
                        to="patients.record",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vaccine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data/hora em que o registro foi criado"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data/hora da ultima atualização"
                    ),
                ),
                (
                    "is_activate",
                    models.BooleanField(default=True, help_text="Indica se o registro está ativo"),
                ),
                ("name", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("lot", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccines",
                        to="patients.record",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
