# Generated by Django 5.2.6 on 2025-10-10 18:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora em que o registro foi criado')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora da ultima atualização')),
                ('is_activate', models.BooleanField(default=True, help_text='Indica se o registro está ativo')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('cpf', models.CharField(blank=True, help_text='Somente números, sem pontos ou traços.', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve ter 11 dígitos numéricos.', regex='^\\d{11}$')])),
                ('birth_certificate_number', models.CharField(blank=True, help_text='Número da certidão de nascimento (se disponível).', max_length=50, null=True, unique=True)),
                ('gestational_age_weeks', models.PositiveSmallIntegerField()),
                ('gestational_age_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('birth_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('head_circumference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=200, verbose_name='Nome do Responsável')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone de Contato')),
                ('address_street', models.CharField(blank=True, max_length=255, verbose_name='Logradouro')),
                ('address_number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('address_complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('address_neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('address_city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('address_state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('address_zip_code', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora em que o registro foi criado')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora da ultima atualização')),
                ('is_activate', models.BooleanField(default=True, help_text='Indica se o registro está ativo')),
                ('record_type', models.CharField(choices=[('discharge', 'Alta'), ('consultation', 'Consulta'), ('followup', 'Seguimento')], max_length=20)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Local do Atendimento')),
                ('professional', models.CharField(blank=True, max_length=150, null=True, verbose_name='Profissional/Cargo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterdisciplinaryEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora em que o registro foi criado')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora da ultima atualização')),
                ('is_activate', models.BooleanField(default=True, help_text='Indica se o registro está ativo')),
                ('area', models.CharField(choices=[('nursing', 'Enfermagem'), ('physiotherapy', 'Fisioterapia'), ('speech', 'Fonoaudiologia'), ('psychology', 'Psicologia'), ('social_work', 'Serviço Social'), ('occupational_therapy', 'Terapia Ocupacional')], max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_evaluations', to='patients.record')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora em que o registro foi criado')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora da ultima atualização')),
                ('is_activate', models.BooleanField(default=True, help_text='Indica se o registro está ativo')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('specialty', models.CharField(blank=True, max_length=50, null=True)),
                ('professional', models.CharField(blank=True, max_length=100, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='patients.record')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora em que o registro foi criado')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora da ultima atualização')),
                ('is_activate', models.BooleanField(default=True, help_text='Indica se o registro está ativo')),
                ('type', models.CharField(max_length=50)),
                ('result', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='patients.record')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DischargeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora em que o registro foi criado')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora da ultima atualização')),
                ('is_activate', models.BooleanField(default=True, help_text='Indica se o registro está ativo')),
                ('chronological_age_days', models.PositiveIntegerField(blank=True, null=True)),
                ('corrected_age_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('head_circumference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feeding_type', models.CharField(choices=[('breastfeeding', 'SME'), ('mixed', 'SM+Fórmula'), ('formula', 'Fórmula')], max_length=20)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge', to='patients.record')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora em que o registro foi criado')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora da ultima atualização')),
                ('is_activate', models.BooleanField(default=True, help_text='Indica se o registro está ativo')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Peso (g)')),
                ('weighed_without_diaper', models.BooleanField(default=True, verbose_name='Pesado sem fralda')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Comprimento (cm)')),
                ('head_circumference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Perímetro Cefálico (cm)')),
                ('feeding_type', models.CharField(blank=True, choices=[('exclusive', 'Aleitamento materno exclusivo'), ('mixed', 'Aleitamento misto'), ('formula', 'Fórmula')], max_length=20, null=True, verbose_name='Tipo alimentar')),
                ('feeding_interval', models.CharField(blank=True, max_length=100, null=True, verbose_name='Intervalo entre mamadas')),
                ('diapers_in_24h', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de fraldas em 24h')),
                ('breastfeeding_observation', models.CharField(blank=True, choices=[('ok', 'Pega/posição OK'), ('correction', 'Necessita correção')], max_length=20, null=True, verbose_name='Observação da mamada')),
                ('uses_pacifier', models.BooleanField(blank=True, null=True, verbose_name='Uso de mamadeira/chupeta')),
                ('kangaroo_hours_per_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Horas em contato pele a pele no dia')),
                ('kangaroo_difficulties', models.TextField(blank=True, null=True, verbose_name='Dificuldades ou interrupções')),
                ('warning_signs_observations', models.TextField(blank=True, null=True, verbose_name='Observações adicionais sobre sinais de alerta')),
                ('family_arrival_notes', models.TextField(blank=True, null=True, verbose_name='Como foi a chegada em casa?')),
                ('family_support_notes', models.TextField(blank=True, null=True, verbose_name='Quem está ajudando e de que forma?')),
                ('guidance_given', models.TextField(blank=True, null=True, verbose_name='Orientações dadas')),
                ('return_plan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plano de retorno agendado')),
                ('next_appointment_date', models.DateField(blank=True, null=True, verbose_name='Data do próximo retorno')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_details', to='patients.record')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicalWarningSign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora em que o registro foi criado')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora da ultima atualização')),
                ('is_activate', models.BooleanField(default=True, help_text='Indica se o registro está ativo')),
                ('type', models.CharField(choices=[('hypothermia', 'Temperatura ≤ 36,5°C (hipotermia)'), ('respiratory_pause', 'Pausas respiratórias ≥ 20 seg ou cianose'), ('skin_perfusion', 'Perfusão da pele: cianose, palidez, marmórea'), ('regurgitation', 'Regurgitação ou vômitos frequentes'), ('hypoactivity', 'Sinais de hipoatividade ou irritabilidade'), ('jaundice', 'Icterícia visível ou persistente'), ('abnormalities', 'Sopro, hérnia abdominal ou fontanela abaulada')], max_length=30, verbose_name='Tipo de Sinal')),
                ('is_present', models.BooleanField(default=False, verbose_name='Presente')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warning_signs', to='patients.record')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicalEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora em que o registro foi criado')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora da ultima atualização')),
                ('is_activate', models.BooleanField(default=True, help_text='Indica se o registro está ativo')),
                ('type', models.CharField(choices=[('pediatric', 'Pediátrica'), ('neurologic', 'Neurológica'), ('cardiac', 'Cardiológica'), ('visual', 'Visual'), ('auditory', 'Auditiva')], max_length=20)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('altered', 'Alterada')], max_length=10)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_evaluations', to='patients.record')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora em que o registro foi criado')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora da ultima atualização')),
                ('is_activate', models.BooleanField(default=True, help_text='Indica se o registro está ativo')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('lot', models.CharField(blank=True, max_length=50, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='patients.record')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
