# Generated by Django 5.2.6 on 2025-10-20 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargerecord',
            name='chronological_age_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dischargerecord',
            name='corrected_age_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cpf',
            field=models.CharField(blank=True, help_text='Somente números, sem pontos ou traços.', max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve ter 11 dígitos numéricos.', regex='^\\d{11}$')]),
        ),
    ]
