# Generated by Django 5.2.6 on 2025-09-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_complement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_state',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_zip_code',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone de Contato'),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do Responsável'),
        ),
    ]
