# Generated by Django 5.2.6 on 2025-10-22 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_alter_dischargerecord_chronological_age_days_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="record",
        ),
        migrations.RemoveField(
            model_name="vaccine",
            name="record",
        ),
        migrations.AddField(
            model_name="exam",
            name="patient",
            field=models.ForeignKey(
                default="ea3904fa-9bce-405f-b606-4d4d568e12c0",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="patients.patient",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vaccine",
            name="patient",
            field=models.ForeignKey(
                default="ea3904fa-9bce-405f-b606-4d4d568e12c0",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vaccines",
                to="patients.patient",
            ),
            preserve_default=False,
        ),
    ]
