# Generated by Django 5.2.6 on 2025-10-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_dischargerecord_chronological_age_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargerecord',
            name='chronological_age_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dischargerecord',
            name='corrected_age_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
