# Generated by Django 5.2.6 on 2025-09-26 01:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_address_city_patient_address_complement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora em que o registro foi criado')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora da ultima atualização')),
                ('is_activate', models.BooleanField(default=True, help_text='Indica se o registro está ativo')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Peso (g)')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Comprimento (cm)')),
                ('head_circumference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Perímetro Cefálico (cm)')),
                ('feeding_type', models.CharField(blank=True, choices=[('breastfeeding', 'Aleitamento materno exclusivo (SME)'), ('mixed', 'SME + Fórmula'), ('formula', 'Fórmula Infantil')], max_length=20, null=True, verbose_name='Tipo de Alimentação')),
                ('breastfeeding_observation', models.CharField(blank=True, choices=[('ok', 'Pega/posição OK'), ('correction_needed', 'Necessita correção')], max_length=20, null=True, verbose_name='Observação da Mamada')),
                ('kangaroo_hours_per_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Horas em Posição Canguru por dia')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_details', to='patients.record')),
            ],
            options={
                'verbose_name': 'Registro de Consulta',
                'verbose_name_plural': 'Registros de Consulta',
            },
        ),
        migrations.CreateModel(
            name='ClinicalWarningSign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora em que o registro foi criado')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora da ultima atualização')),
                ('is_activate', models.BooleanField(default=True, help_text='Indica se o registro está ativo')),
                ('type', models.CharField(choices=[('hypothermia', 'Temperatura ≤ 36,5°C (hipotermia)'), ('respiratory_pause', 'Pausas respiratórias ≥ 20 seg ou cianose'), ('skin_perfusion', 'Perfusão da pele: cianose, palidez, marmórea'), ('regurgitation', 'Regurgitação ou vômitos frequentes'), ('hypoactivity', 'Sinais de hipoatividade ou irritabilidade'), ('jaundice', 'Icterícia visível ou persistente')], max_length=30, verbose_name='Tipo de Sinal')),
                ('is_present', models.BooleanField(default=False, verbose_name='Presente')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warning_signs', to='patients.record')),
            ],
            options={
                'verbose_name': 'Sinal Clínico de Alerta',
                'verbose_name_plural': 'Sinais Clínicos de Alerta',
                'unique_together': {('record', 'type')},
            },
        ),
    ]
