# Generated by Django 5.2.6 on 2025-09-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_consultationrecord_clinicalwarningsign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalwarningsign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='consultationrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='clinicalwarningsign',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='diapers_in_24h',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de fraldas em 24h'),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='family_arrival_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Como foi a chegada em casa?'),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='family_support_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Quem está ajudando e de que forma?'),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='feeding_interval',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Intervalo entre mamadas'),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='guidance_given',
            field=models.TextField(blank=True, null=True, verbose_name='Orientações dadas'),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='kangaroo_difficulties',
            field=models.TextField(blank=True, null=True, verbose_name='Dificuldades ou interrupções'),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='next_appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do próximo retorno'),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='return_plan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plano de retorno agendado'),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='uses_pacifier',
            field=models.BooleanField(blank=True, null=True, verbose_name='Uso de mamadeira/chupeta'),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='warning_signs_observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações adicionais sobre sinais de alerta'),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='weighed_without_diaper',
            field=models.BooleanField(default=True, verbose_name='Pesado sem fralda'),
        ),
        migrations.AddField(
            model_name='record',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Local do Atendimento'),
        ),
        migrations.AddField(
            model_name='record',
            name='professional',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Profissional/Cargo'),
        ),
        migrations.AlterField(
            model_name='clinicalwarningsign',
            name='type',
            field=models.CharField(choices=[('hypothermia', 'Temperatura ≤ 36,5°C (hipotermia)'), ('respiratory_pause', 'Pausas respiratórias ≥ 20 seg ou cianose'), ('skin_perfusion', 'Perfusão da pele: cianose, palidez, marmórea'), ('regurgitation', 'Regurgitação ou vômitos frequentes'), ('hypoactivity', 'Sinais de hipoatividade ou irritabilidade'), ('jaundice', 'Icterícia visível ou persistente'), ('abnormalities', 'Sopro, hérnia abdominal ou fontanela abaulada')], max_length=30, verbose_name='Tipo de Sinal'),
        ),
        migrations.AlterField(
            model_name='consultationrecord',
            name='breastfeeding_observation',
            field=models.CharField(blank=True, choices=[('ok', 'Pega/posição OK'), ('correction', 'Necessita correção')], max_length=20, null=True, verbose_name='Observação da mamada'),
        ),
        migrations.AlterField(
            model_name='consultationrecord',
            name='feeding_type',
            field=models.CharField(blank=True, choices=[('exclusive', 'Aleitamento materno exclusivo'), ('mixed', 'Aleitamento misto'), ('formula', 'Fórmula')], max_length=20, null=True, verbose_name='Tipo alimentar'),
        ),
        migrations.AlterField(
            model_name='consultationrecord',
            name='kangaroo_hours_per_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Horas em contato pele a pele no dia'),
        ),
    ]
