# Generated by Django 5.2.6 on 2025-11-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0005_merge_20251029_1754"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="status",
            field=models.CharField(
                choices=[("draft", "Rascunho"), ("final", "Finalizado")],
                db_index=True,
                default="final",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
