# Generated by Django 5.2.6 on 2025-11-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0005_merge_20251029_1754"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="is_active",
        ),
        migrations.AddField(
            model_name="patient",
            name="in_follow_up",
            field=models.BooleanField(
                default=True,
                help_text="Indica se o paciente está em acompanhamento ativo.",
                verbose_name="Em Acompanhamento",
            ),
        ),
    ]
