# Generated by Django 5.2.6 on 2025-11-05 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_delete_filho"),
        ("patients", "0006_remove_patient_is_active_patient_in_follow_up"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="guardian_name",
        ),
        migrations.AddField(
            model_name="patient",
            name="guardian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to="accounts.paisprofile",
                verbose_name="Responsável (Conta de Acesso)",
            ),
        ),
    ]
