# Generated by Django 5.2.6 on 2025-11-03 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0006_record_status"),
        ("patients", "0006_remove_patient_is_active_patient_in_follow_up"),
    ]

    operations = []
