# Generated by Django 5.2.7 on 2025-11-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_merge_20251103_1808'),
        ('patients', '0007_remove_patient_contact_phone_and_more'),
    ]

    operations = [
    ]
