# Generated by Django 5.2.6 on 2025-10-17 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_alter_dischargerecord_chronological_age_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('template_path', models.CharField(max_length=200, verbose_name='Caminho do Template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('context_variables', models.JSONField(default=list, help_text='Lista de variáveis disponíveis no template', verbose_name='Variáveis de Contexto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Template de Email',
                'verbose_name_plural': 'Templates de Email',
            },
        ),
        migrations.CreateModel(
            name='EmailAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('critical_warning', 'Sinal de Alerta Crítico'), ('weight_gain', 'Problema no Ganho de Peso'), ('missed_appointment', 'Consulta Perdida'), ('system', 'Alerta do Sistema')], max_length=20, verbose_name='Tipo de Alerta')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('acknowledged', 'Reconhecido'), ('resolved', 'Resolvido'), ('cancelled', 'Cancelado')], default='pending', max_length=15, verbose_name='Status')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='Dados de Contexto')),
                ('recipients', models.JSONField(default=list, verbose_name='Destinatários')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Envios')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Envio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconhecido em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_alerts', to='patients.patient')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_alerts', to='patients.record')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Email',
                'verbose_name_plural': 'Alertas de Email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'alert_type'], name='emails_emai_status_3b27ab_idx'), models.Index(fields=['patient', 'status'], name='emails_emai_patient_abb091_idx'), models.Index(fields=['created_at'], name='emails_emai_created_90b669_idx')],
            },
        ),
    ]
