# Generated by Django 5.2.6 on 2025-10-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='context_variables',
            field=models.JSONField(blank=True, default=list, help_text='Lista de variáveis disponíveis no template', null=True, verbose_name='Variáveis de Contexto'),
        ),
    ]
